/*
SQLyog Professional v13.1.1 (64 bit)
MySQL - 5.7.14 : Database - twoquake_qnut
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `tops_tasklog` */

CREATE TABLE IF NOT EXISTS `tops_tasklog` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `time` DATETIME DEFAULT NULL,
  `type` INT(10) UNSIGNED DEFAULT NULL,
  `message` VARCHAR(256) DEFAULT NULL,
  `taskname` VARCHAR(128) DEFAULT NULL,
  `active` TINYINT(4) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=491 DEFAULT CHARSET=latin1;

/*Table structure for table `tops_taskqueue` */

CREATE TABLE IF NOT EXISTS `tops_taskqueue` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `frequency` VARCHAR(32) NOT NULL DEFAULT '24 Hours',
  `taskname` VARCHAR(128) DEFAULT NULL,
  `namespace` VARCHAR(128) DEFAULT NULL,
  `startdate` DATE DEFAULT NULL,
  `enddate` DATE DEFAULT NULL,
  `inputs` VARCHAR(512) DEFAULT NULL,
  `comments` TEXT,
  `active` TINYINT(4) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=99 DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
